import requests
from DAXXMUSIC import app
from config import BOT_USERNAME
from pyrogram.enums import ChatAction, ParseMode
from pyrogram import filters

# List of vulgar words to check against
vulgar_words = ["vulgafwords", "vulgarwords", "vulgarwords"]

@app.on_message(filters.command(["aigenimg", "aiimg"], prefixes=["+", ".", "/", "-", "", "$", "#", "&"]))
async def generate_image(bot, message):
    try:
        start_time = time.time()
        await bot.send_chat_action(message.chat.id, ChatAction.TYPING)

        if len(message.command) < 2:
            await message.reply_text("Example:\n\n/generate A beautiful sunset over the mountains")
        else:
            prompt = message.text.split(' ', 1)[1]

            # Check for vulgar words
            if any(word in prompt.lower() for word in vulgar_words):
                await message.reply_text(
                    "❌ <b>You cannot generate images with vulgar prompts.</b>",
                    parse_mode=ParseMode.HTML
                )
                return

            api_url = f"https://aiimage.hellonepdevs.workers.dev/?prompt={prompt}&state=url"

            try:
                response = requests.get(api_url)
                response.raise_for_status()
                data = response.json()

                # Send generated image
                await bot.send_photo(
                    chat_id=message.chat.id,
                    photo=data["image_url"],
                    caption="🎨 <b>Image Generated by @BotUsername</b>",
                    parse_mode=ParseMode.HTML
                )
            except Exception as e:
                await message.reply_text(
                    f"❌ <b>Error:</b> <i>{str(e)}</i>",
                    parse_mode=ParseMode.HTML
                )

    except Exception as e:
        await message.reply_text(f"**á´‡Ê€Ê€á´Ê€: {e}")
        
